name: Back Unit Tests

on: push

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        working-directory: ./Back
        run: |
          composer install
          php bin/phpunit   

          